Haz refactor
ppapasani1/ClimateModel_E2E pull request #11
Opened 2020-10-23 18:18 UTC by ppapasani1

PR to refactor FL hazard code.

- Modularize the FL hazard component. Optimize logic by cell(Instead of Locid)
- Added RMS Version of QuadKey conversion.
- Added hazard smoke tests for APFL, EUFL, USFL models. (Runs on both Linux and Windows)
![image](https://user-images.githubusercontent.com/37124509/97039546-753d7c80-1521-11eb-8cb1-d301514e7b9a.png)

- Large smoke test baseline is stored at `\\ca1fs01\me_dev\modcert\E2E_Smoketests` or `/me-dev/modcert/E2E_Smoketests`
- The new code will be structure into Module, Model, and tests as shown below. 
```
├── Model
│   ├── APFL
│   ├── EUFL
│   ├── NZFL
│   └── USFL
├── Module
│   └── hazard
└── tests
    └── resources
        ├── apfl_hazard_test
        ├── eufl_hazard_test
        ├── eufl_hazard_test2
        └── usfl_hazard_test
```

Note- Still old code is not removed. Will remove once complete integration is done in the upcoming PRs.

2020-10-23 23:35 UTC, ppapasani1 commented
@ssura-rms @rishikeshkumar9 Please keep an eye on this PR. 70-80% of the existing FL hazard code is refactored. Adding you both as reviewers.

2020-10-27 16:29 UTC, zsun-rms commented on climateE2E/E2E_Prototype_Main.R
> +isDockerRun <- T
Is there a place for windows runs to set it to false?

2020-10-27 20:07 UTC, zsun-rms commented on climateE2E/HD_Climate_E2E.R
> +  configfile <- if(isDockerRun) "D:/Pruthvi/gitProjects/ClimateModel_E2E/climateE2E/climateE2E/tests/resources/usfl_hazard_test/config.json" else "config.yml"
E2E should support both `yml` and `json` format for loading config file, not that docker run accept `json` format else accept 'yml'

2020-10-29 18:41 UTC, sthupakula-rms requested changes
We are in the right direction. More cleanup should be taken once the migration is structurally complete. A few remarks below.

2020-10-29 18:41 UTC, sthupakula-rms commented on climateE2E/Model/EUFL/eufl_hazard.R
> +## Place holder to override Model specific setting
Such structure for models looks Good 👍

2020-10-29 18:41 UTC, sthupakula-rms commented on climateE2E/tests/compare_dt.R
> +library(data.table)
May move to common library loader

2020-10-29 18:41 UTC, sthupakula-rms commented on climateE2E/tests/fl_hazard_tests.R
> +ModelData <- if(os=="win") "//ca1fs01/mc_stage/NGDLMDATA" else "/NGDLMDATA"
Nice 👍

2020-10-29 18:41 UTC, sthupakula-rms commented on climateE2E/tests/resources/apfl_hazard_test/config.json
> +    "EDScsv": "D:/Pruthvi/gitProjects/ClimateModel_E2E/climateE2E/climateE2E/tests/resources/apfl_hazard_test/FlatExposure__batch0.csv",
Can we provide relative referencing here somehow, so that anyone can run the tests?

2020-10-29 18:41 UTC, sthupakula-rms commented on climateE2E/tests/resources/apfl_hazard_test/config.json
> +    "OutFolder": "D:/Pruthvi/gitProjects/ClimateModel_E2E/climateE2E/climateE2E/tests/resources/apfl_hazard_test/TestResult",
same as above, and for rest of the tests.

2020-10-29 19:47 UTC, ppapasani1 commented on climateE2E/E2E_Prototype_Main.R
> +isDockerRun <- T
Will remove this in the final clean. These variables are being used when running against the old code.

2020-10-29 19:48 UTC, ppapasani1 commented on climateE2E/HD_Climate_E2E.R
> +  configfile <- if(isDockerRun) "D:/Pruthvi/gitProjects/ClimateModel_E2E/climateE2E/climateE2E/tests/resources/usfl_hazard_test/config.json" else "config.yml"
Agree. It will be the JSON for all runtimes. I've already cleaned up in the subsequent PR.

2020-10-29 19:51 UTC, ppapasani1 commented on climateE2E/tests/resources/apfl_hazard_test/config.json
> +    "OutFolder": "D:/Pruthvi/gitProjects/ClimateModel_E2E/climateE2E/climateE2E/tests/resources/apfl_hazard_test/TestResult",
Yes. I already fixed it in the subsequent PR.

2020-10-29 19:51 UTC, ppapasani1 commented on climateE2E/tests/resources/apfl_hazard_test/config.json
> +    "EDScsv": "D:/Pruthvi/gitProjects/ClimateModel_E2E/climateE2E/climateE2E/tests/resources/apfl_hazard_test/FlatExposure__batch0.csv",
Yes. I already fixed in the subsequent PR.

2020-10-29 20:12 UTC, ppapasani1 commented on climateE2E/Module/e2e_logger.R
> +if("logger" %in% (.packages())){
Yes, they will be loaded at the very initial level. This is just an additional check in case if we are calling logging from any other external codes, like for testing. 
For docker, we have a shell script that installs all the required packages, we need to add that package name to the shell script.

2020-10-29 20:12 UTC, ppapasani1 commented on climateE2E/Module/hazard/fl_calculate.R
> +combineFloodDepth <- function(events1d, events2d, eventsra, includeRA, useCorrectTimeStampMethodology){
Missing the return function. Will add it.

2020-11-02 14:47 UTC, ppapasani1 commented
> We are in the right direction. More cleanup should be taken once the migration is structurally complete. A few remarks below.

@sthupakula-rms I've addressed most of the comments in the follow-up PR. Can you please approve this?

2020-11-02 18:33 UTC, sthupakula-rms approved these changes

2020-11-02 18:41 UTC, merged