Apfl nzfl v21
ppapasani1/ClimateModel_E2E pull request #8
Opened 2020-09-29 12:51 UTC by rishikeshkumar9

2020-09-29 16:33 UTC, ppapasani1 approved these changes

2020-09-29 17:59 UTC, sthupakula-rms commented on Flood_E2E/VulnCache.R
> +if(cnfg$Model=="APFL" || cnfg$Model=="NZFL"){
`toupper(cnfg$Model)`

2020-09-29 18:01 UTC, sthupakula-rms requested changes
Thank you.
One change request and a question.

2020-09-29 18:01 UTC, sthupakula-rms commented on Flood_E2E/VulnCache.R
> +if(cnfg$Model=="APFL" || cnfg$Model=="NZFL"){
Do we really have two variables `config` and `cnfg`, or is there a typo? There's a `config$Version == 15` in the code change above and here there's a `config$Version == 15`

2020-09-30 06:04 UTC, rishikeshkumar9 commented on Flood_E2E/VulnCache.R
> +if(cnfg$Model=="APFL" || cnfg$Model=="NZFL"){
cnfg is the variable used when we read config file directly from the path of test folder. The same file is renamed config==cnfg while running hazard or vulnerability . For uniformity i think  "config" should be used for the two changes. I will replace cnfg with config.

2020-09-30 07:01 UTC, rishikeshkumar9 reviewed
added to update the APFL version 20

2020-09-30 07:04 UTC, merged